services:
  php:
    build:
      context: ./back-end
    container_name: scfm_php
    working_dir: /var/www/html
    depends_on:
      - db

  nginx:
    build:
      context: ./front-end
    container_name: scfm_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front-end/nginx/certs:/etc/nginx/ssl:ro
    depends_on:
      - php

  db:
    image: mysql:8.0.36
    container_name: mysql
    env_file: ".env"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: