services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      HOST: db
    depends_on:
      - db
  db:
    image: mysql:8.2
    restart: always
    env_file:
      - .env
    volumes:
      - scfm_db_data:/var/lib/mysql
volumes:
  scfm_db_data: