server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/self-signed.crt;
    ssl_certificate_key /etc/nginx/ssl/self-signed.key;

    root /var/www/html/public;

    location /api {
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        include fastcgi_params;
    }

    location / {
        root /var/www/react;
        index index.html;
        try_files $uri/ /index.html =404;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}

server {
    listen 80;
    server_name localhost;

    return 301 https://$host$request_uri;
}